app/models.py
from flask_login import UserMixin
from . import db 

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150), nullable=False)
    tasks = db.relationship('Task', cascade="all, delete")

    def __str__(self):
        return self.username

class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000), nullable=False)
    status = db.Column(db.Boolean, nullable=False, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

app/__init__.py
from flask import Blueprint, Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow



DB_NAME = "database.db"
db = SQLAlchemy()
ma = Marshmallow()

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'aecq#hbq7&afiohd@!6d*'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://taskmanager_db_t4ml_user:u0cBoSU3RGyoQjVsJb699XcfSFz0aNui@dpg-cfmd204gqg469ktodc30-a.oregon-postgres.render.com/taskmanager_db_t4ml'
    # 'postgresql://localhost:5432/taskmanager_db'
    # f'sqlite:///{DB_NAME}'

    db.init_app(app)
    ma.init_app(app)

    from .views import views
    from .auth import auth
    from .api import api_bp

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(api_bp)
    
    from app.models import User

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))


    with app.app_context():
        # db.drop_all()
        db.create_all()

    print(app.url_map)      

    return app

app/api/__init__.py
from flask import Blueprint
from flask_restful import Api

api_bp = Blueprint('api', __name__, url_prefix='/api') 
api = Api(api_bp)

from . import resources

app/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user

from app.models import *

auth = Blueprint('auth', __name__)

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        username = request.form['username']
        password1 = request.form['password1']
        password2 = request.form['password2']
        
        user = User.query.filter_by(username=username).first()

        if user:
            flash('Username already exists.', category='error')
        elif len(username) < 4:
            flash('Username must be greater than 3 characters.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(username=username, password=generate_password_hash(
                password1, method='sha256'))

            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')

            return redirect(url_for('views.home'))

    return render_template('sign-up.html', title="Sign up") 

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form["username"]
        password = request.form['password']

        user = User.query.filter_by(username=username).first()

        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Username does not exist.', category='error')
    return render_template('login.html', title="Log in")

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))
    

app/views.py
from flask import Blueprint, redirect, render_template, request, flash, url_for
from flask_login import login_required, current_user
from app.models import *
from werkzeug.security import generate_password_hash, check_password_hash

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    user_id=current_user.id
    tasks = Task.query.filter_by(user_id=user_id).all()
    if request.method == "POST":
        task_id = request.form['button']
        task = Task.query.get_or_404(task_id)
       
        if task.status is False:
            task.status = True
        else:
            task.status = False
        db.session.commit()
        return redirect(url_for('views.home'))
    
    return render_template('tasks.html', title="Tasks", tasks=tasks)


@views.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    user = User.query.filter_by(id=current_user.id).first()
    uncompleted_tasks = count_uncompleted_tasks(user)
    
    if request.method == "POST":
        new_username = request.form['username']
        password = request.form['password']
        new_password = request.form['new_password']
        old_password = user.password

        if not password:
            if check_username(user.username, new_username):
                user.username = new_username
                db.session.commit()
                flash('Profile updated!', category='success')
            return redirect(url_for('views.profile'))
        elif check_password(password, new_password, old_password) and check_username(user.username, new_username):
            user.username = new_username
            user.password = generate_password_hash(new_password)
            db.session.commit()

            flash('Profile updated!', category='success')
            return redirect(url_for('views.profile'))
        
        
    return render_template('profile.html', title="Profile", user=user, uncompleted_tasks=uncompleted_tasks)


@views.route('/profile-delete/<int:user_id>')
@login_required
def delete_profile(user_id):
    user = User.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()
    flash('Your profile was deleted!', category='success')
    return redirect(url_for('auth.sign_up'))


@views.route('/task/<int:task_id>', methods=['GET', 'POST'])
@login_required
def task(task_id):
    task = Task.query.get_or_404(task_id)
    if request.method == "POST":
        task.data = request.form['data']
        db.session.commit()

    return render_template('update-task.html', title="Task", task=task)


@views.route('/task-create', methods=['GET', 'POST'])
@login_required
def create_task():
    if request.method == "POST":
        data = request.form['data']
        new_task = Task(data=data, user_id=current_user.id)
        db.session.add(new_task)
        db.session.commit()
        
        return redirect(url_for('views.home'))

    return render_template('create-task.html', title="New task")


@views.route('/task-delete/<int:task_id>')
@login_required
def delete_task(task_id):
    task = Task.query.get_or_404(task_id)
    db.session.delete(task)
    db.session.commit()
    flash('Your task was deleted!', category='success')
    return redirect(url_for('views.home'))


def check_password(password, new_password, old_password):
    
    if not check_password_hash(old_password, password):
        flash('Password is wrong', category='error')
        return False
    elif len(new_password) < 7:
        flash('Password must be at least 7 characters.', category='error')
        return False

    return True

def check_username(username, new_username):
    if username != new_username:
        user = User.query.filter_by(username=new_username).first()
    else:
        user = None
    
    if user:
        flash('User with such username already exists.', category='error')
        return False

    elif len(username) < 4:
        flash('Username must be greater than 3 characters.', category='error')
        return False

    return True

def count_uncompleted_tasks(user):
    tasks = Task.query.filter_by(user_id=user.id).all()
    counter = 0
    for task in tasks:
        if task.status is False:
            counter = counter+1

    return counter

app/templates/base.html
<!DOCTYPE html>
<link type="text/css" href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet"/>
<html>
<head>
    <title> {{ title }}</title>
    {%- block mainmenu -%}
    <ul class="mainmenu">
        <li><a href="{{url_for('views.profile', user_id=current_user.id)}}">{{current_user}}</a></li>
        <li><a href="{{url_for('views.home')}}">tasks</a></li>
        <li><a href="{{url_for('views.create_task')}}">new task</a></li>
    </ul>
    {% endblock mainmenu -%}
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

app/templates/create-task.html
{% extends 'base.html' %}

{% block body %}

<form method="post">
    <div class="updateTask">
        <div class="inputData">
            <textarea class="input2" name="data" placeholder="Type..."></textarea>
        </div>
        <input type="submit" class="profileBtn" value="Add">
    </div>
</form>

{% endblock %}

app/templates/login.html
<!DOCTYPE html>
<link type="text/css" href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet"/>
<html>
<head>
    <title> {{ title }}</title>
</head>
<body>
    <div class="signupFrm">
        <form method="post" class="form">
            {% for cat, msg in get_flashed_messages(True) %}
          <div class="flash {{ cat }}">{{ msg }}</div>
            {% endfor %}
          <h1 class="title">Log in</h1>
        
          <div class="inputContainer">
            <input type="text" class="input" placeholder="a" name="username">
            <label for="username" class="label">Username</label>
          </div>
    
          <div class="inputContainer">
            <input type="text" class="input" placeholder="a" name="password">
            <label for="password" class="label">Password</label>
          </div>
    
          <input type="submit" class="submitBtn" value="Log in">
            <p style="color: #26233a;">Don't have an account?  <a href="{{url_for('auth.sign_up')}}">Sign up</a></p>            
        </form>
      </div>
</body>

app/templates/profile.html
{% extends 'base.html' %}
{% block body %}


<form method="post" class="profileform">
    {% for cat, msg in get_flashed_messages(True) %}
    <div class="flash {{ cat }}">{{ msg }}</div>
    {% endfor %}
    <h1 class="title" style="margin-bottom: 30px">User profile</h1>
    <div class="taskstodo"><p >Tasks to do: {{uncompleted_tasks}}</p></div>
    <div class="inputContainer">
        <input type="text" class="input" placeholder="a" name="username" value="{{ user.username }}">
        <label for="username" class="label">Username</label>
    </div>
    <div class="inputContainer">
        <input type="text" class="input" placeholder="a" name="password">
        <label for="password1" class="label">Password</label>
    </div>

    <div class="inputContainer">
        <input type="text" class="input" placeholder="a" name="new_password">
        <label for="password1" class="label">New password</label>
    </div>
    <input type="submit" class="profileBtn" value="Update">
    <a class="profileBtn" style="background-color: #ea9a97;" href="{{ url_for('auth.logout') }}">Log out</a>
    <a class="profileBtn" style="background-color: #ea9a97;" href="{{url_for('views.delete_profile', user_id=user.id)}}">Delete</a>
</form>
{% endblock %}

app/templates/sign-up.html
<!DOCTYPE html>
<link type="text/css" href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet"/>
<html>
<head>
    <title> {{ title }}</title>
</head>
<body>
    <div class="signupFrm">
        <form method="post" class="form">
            {% for cat, msg in get_flashed_messages(True) %}
          <div class="flash {{ cat }}">{{ msg }}</div>
            {% endfor %}
          <h1 class="title">Sign up</h1>
        
          <div class="inputContainer">
            <input type="text" class="input" placeholder="a" name="username">
            <label for="username" class="label">Username</label>
          </div>
    
          <div class="inputContainer">
            <input type="text" class="input" placeholder="a" name="password1">
            <label for="password1" class="label">Password</label>
          </div>
    
          <div class="inputContainer">
            <input type="text" class="input" placeholder="a" name="password2">
            <label for="password2" class="label">Confirm Password</label>
          </div>
          <input type="submit" class="submitBtn" value="Sign up">
            <p style="color: #26233a;">Have an account?  <a href="{{url_for('auth.login')}}">Log in </a></p>            
        </form>
      </div>
</body>

app/templates/tasks.html
{% extends 'base.html' %}

{% block body %}
{% for cat, msg in get_flashed_messages(True) %}
    <div class="flash {{ cat }}">{{ msg }}</div>
{% endfor %}
<h1 class="title" style="text-align: center;">My Tasks</h1>
<!-- <ol type = "1"> -->
    {% for task in tasks %}
    
        <div class="cntr">
            <!-- <li> -->
            {% if task.status == false %}
                <a href="{{url_for('views.task', task_id=task.id)}}" class="element">
                {{ task.data }}
                </a>
            {% else %}
                <a href="{{url_for('views.task', task_id=task.id)}}" style="text-decoration: line-through;" class="element">
                {{ task.data }}
                </a>
            {% endif %}
            <form method="post">
                {% if task.status == false %}
                <button class="button-81" value="{{ task.id }}" name="button">Completed</button> 
                {% else %}
                <button class="button-81" value="{{ task.id }}" name="button">Uncompleted</button> 
                {% endif %}
            </form>
            <!-- </li> -->
        </div>
    {% endfor %}
<!-- </ol> -->
{% endblock %}

app/templates/update-task.html
{% extends 'base.html' %}

{% block body %}
  
<form method="post">
    <div class="updateTask">
        <div class="inputData">
            <textarea class="input2" name="data">{{ task.data }}</textarea>
        </div>
        <input type="submit" class="profileBtn" value="Edit">
    <a class="profileBtn" style="background-color: #ea9a97;" href="{{url_for('views.delete_task', task_id=task.id)}}">Delete</a>
    </div>
</form>

{% endblock %}